tasks:
  - name: Spring Boot (Gradle)
    init: |
      cd shop/backend
      curl -s "https://get.sdkman.io" | bash
      source "$HOME/.sdkman/bin/sdkman-init.sh"
      yes | sdk install java 17.0.4-tem
      ./gradlew build -x test
    command: |
      cd shop/backend
      ./gradlew bootRun
  - name: React & TypeScript
    init: |
      cd shop/frontend
      npm install
    command: |
      cd shop/frontend
      REACT_APP_GITPOD_WORKSPACE_URL=$(gp url 3000) npm start
ports:
  - port: 8080
    onOpen: open-preview
    visibility: public
  - port: 3000
    onOpen: open-browser
    visibility: public