tasks:
  - name: Spring Boot (Gradle)
    init: |
      cd shop/backend
      curl -s "https://get.sdkman.io" | bash
      source "$HOME/.sdkman/bin/sdkman-init.sh"
      export SDKMAN_AUTO_ANSWER=true
      sdk install java 17.0.4-tem
      sdk use java 17.0.4-tem
      ./gradlew build -x test
    command: |
      cd shop/backend
      ./gradlew bootRun
  - name: React & TypeScript
    init: |
      cd shop/frontend
      npm install
    command: |
      cd shop/frontend
      npm start
ports:
  - port: 8080
    onOpen: open-preview
  - port: 3000
    onOpen: open-browser