name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build with Gradle Wrapper
      working-directory: shop/backend
      run: ./gradlew build

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate dependency graph
      working-directory: shop/backend
      run: ./gradlew dependencies --configuration runtimeClasspath

    - name: Upload dependency graph
      uses: actions/upload-artifact@v2
      with:
        name: dependency-graph
        path: shop/backend/build/reports/dependency-graph.json
